apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
  namespace: development
spec:
  # Replicas — загальна кількість інстансів, включно з master
  replicas: 1
  image: docker.dragonflydb.io/dragonflydb/dragonfly
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
